server:
  port: 8081
spring:
  application:
    name: FinancialStatement
  freemarker:
    expose-session-attributes: true

  # ------------- DataBases
  datasource:
    url: jdbc:postgresql://localhost:5432/spy
    username: postgres
    password: Nevada.at1967

    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

  liquibase:
    change-log: classpath:/db/changelog/master.yml

  output:
    ansi:
      enabled: always

  mail:
    host: smtp.gmail.com
    username:
    password:
    port: 587
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true


logging:
  level:
    com.zaxxer.hikari: debug
    org.hibernate.SQL: debug
    root: info
    org:
      springframework:
        security: debug
  file:
    path: logs